{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-extension-backend
  labels:
    app: {{ .Release.Name }}-extension-backend
    app.kubernetes.io/name: extension-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
